[dev]
  command = "yarn dev"

[build]
  command = "yarn generate"
  publish = "dist"
  functions = "functions/lambda"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs8.10" # required for aws-chrome
